services:
  lihc-platform:
    build:
      context: .
      dockerfile: Dockerfile.complete
    container_name: lihc-platform-complete
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped