#\!/bin/bash
export NO_PROXY="localhost,127.0.0.1,0.0.0.0"
echo "🎉 ultrathink v2.7 平台已就绪！"
echo ""
echo "🌐 访问地址："
echo "  • 主面板: http://localhost:8050"
echo "  • API服务: http://localhost:8000"  
echo "  • API文档: http://localhost:8000/docs"
echo ""
echo "✅ 所有v2.7新功能模块已启用："
echo "  • 单细胞RNA-seq分析"
echo "  • AI生物标志物发现"
echo "  • 药物组合预测"
echo "  • 精准医学预测中心"
echo ""
echo "💡 提示：已设置NO_PROXY环境变量绕过系统代理"
